MODEL:
  META_ARCHITECTURE: "OneStageDetector"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  KEYPOINT_ON: False
  BACKBONE:
    NAME: "build_fcos_resnet_pafpn_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"]
    DEFORM_ON_PER_STAGE: [False, True, True, True]
    DEFORM_MODULATED: True
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    NORM: "GN"
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    NMS_TH: 0.6
    PRE_NMS_TOPK_TRAIN: 1000
    PRE_NMS_TOPK_TEST: 500
    LOC_LOSS_TYPE: 'diou'
    NMS_TYPE: 'nms'
    NORM: "GN"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
TEST:
  EVAL_PERIOD: 10000
OUTPUT_DIR: "output/fcos_r50_dcnv2_pafpn"
VERSION: 2

