MODEL:
  META_ARCHITECTURE: "OneStageDetector"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#  WEIGHTS: "output/gfl_fcos_r50_iou/model_final.pth"
  MASK_ON: False
  KEYPOINT_ON: False
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "GFLFCOS"
  FCOS:
    NMS_TH: 0.6
    PRE_NMS_TOPK_TRAIN: 1000
    PRE_NMS_TOPK_TEST: 300
    LOC_LOSS_TYPE: 'diou'
    NMS_TYPE: 'nms'
    NORM: "GN"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  CROP:
    ENABLED: False
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
TEST:
  EVAL_PERIOD: 15000
OUTPUT_DIR: "output/gfl_fcos_r50_test_fixbug"
VERSION: 2

