MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
#  WEIGHTS: "https://hangzh.s3-us-west-1.amazonaws.com/encoding/models/resnest101_detectron-486f69a8.pth"
#  WEIGHTS: "output/faster_cascade_rcnn_ResNeSt_101_FPN_syncbn_range-scale_1x-3627ef78.pth"
  WEIGHTS: "output/faster_cascade_RS_101_9x_enhance/model_2w.pth"
  MASK_ON: False
  BACKBONE:
    NAME: "build_resnest_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    DEPTH: 101
    STRIDE_IN_1X1: False
    RADIX: 2
    NORM: "SyncBN"
  FPN:
    NORM: "SyncBN"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 2000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: CascadeROIHeads
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.05
    BATCH_SIZE_PER_IMAGE: 512 # 512 * 0.25 = 128  lack of GPU memory, can not increase
    POSITIVE_FRACTION: 0.25
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    POOLER_RESOLUTION: 7
    NORM: "SyncBN"
    CLS_AGNOSTIC_BBOX_REG: True
  PIXEL_MEAN: [123.68, 116.779, 103.939]
  PIXEL_STD: [58.393, 57.12, 57.375]
DATASETS:
  TRAIN: ("wheat_coco_train",)
  TEST: ("wheat_coco_val",)
DATALOADER:
  MOSAIC_PROB: 0.33
  MIXUP_PROB: 0.66
SOLVER:
  IMS_PER_BATCH: 12
  BASE_LR: 0.02
  STEPS: (18000, 24000)
  MAX_ITER: 27000
  CHECKPOINT_PERIOD: 2000
INPUT:
  MIN_SIZE_TRAIN: (640, 800)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TRAIN: 1333
  FORMAT: "RGB"
TEST:
  PRECISE_BN:
    ENABLED: True
  EVAL_PERIOD: 2000
OUTPUT_DIR: "output/faster_cascade_RS_101_9x_enhance_0.25"
VERSION: 2

