MODEL:
  META_ARCHITECTURE: "OneStageDetector"
#  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
#  WEIGHTS: "output/fcos_dcnv2_x101_fpn_3x/model_final.pth"
#  WEIGHTS: "output/FCOS_MS_X_101_32x8d_dcnv2_2x.pth"
#  WEIGHTS: "output/fcos_dcnv2_x101_fpn_3x_1024_FVBCMOHSV/model_final.pth"
#  WEIGHTS: "output/fcos_dcnv2_x101_fpn_9x_clahe/model_0020999.pth"
#  WEIGHTS: "output/faster_cascade_rcnn_ResNeSt_101_FPN_syncbn_range-scale_1x-3627ef78.pth"
  WEIGHTS: "https://hangzh.s3-us-west-1.amazonaws.com/encoding/models/resnest101_detectron-486f69a8.pth"
  MASK_ON: False
  KEYPOINT_ON: False
  PIXEL_MEAN: [123.68, 116.779, 103.939]
  PIXEL_STD: [58.393, 57.12, 57.375]
  BACKBONE:
    NAME: "build_fcos_resnest_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
    DEPTH: 101
    STRIDE_IN_1X1: False
    RADIX: 2
    NORM: "SyncBN"
  FPN:
    NORM: "SyncBN"
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    NUM_CLASSES: 1
    NMS_TH: 0.6
    INFERENCE_TH_TEST: 0.05
    PRE_NMS_TOPK_TRAIN: 1000
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 200
    POST_NMS_TOPK_TEST: 200
    LOC_LOSS_TYPE: 'diou'
    NMS_TYPE: 'nms'
    NORM: "GN"
    USE_DEFORMABLE: True
DATASETS:
  TRAIN: ("wheat_coco_train",)
  TEST: ("wheat_coco_val",)
DATALOADER:
  MOSAIC_PROB: (0.0, 0.01)
  MIXUP_PROB: (0.33, 0.34)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  WARMUP_FACTOR: 0.00125
  WARMUP_ITERS: 800
  STEPS: (6000, 8000)
  MAX_ITER: 9000
  CHECKPOINT_PERIOD: 1500
INPUT:
  FORMAT: "RGB"
  CROP:
    ENABLED: False
  MIN_SIZE_TRAIN: (864, 896, 928, 960, 992, 1024)
  MAX_SIZE_TEST: 1024
  MIN_SIZE_TEST: 1024
TEST:
  EVAL_PERIOD: 1500
  PRECISE_BN:
    ENABLED: True
OUTPUT_DIR: "output/fcos_RS_101_fpn_3x_nomosaic"
VERSION: 2

