MODEL:
  META_ARCHITECTURE: "OneStageDetector"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  KEYPOINT_ON: False
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    NUM_CLASSES: 1
    NMS_TH: 0.6
    PRE_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 1000
    LOC_LOSS_TYPE: 'diou'
    NMS_TYPE: 'nms'
    NORM: "GN"
DATASETS:
  TRAIN: ("wheat_coco_train",)
  TEST: ("wheat_coco_val",)
DATALOADER:
  MIXUP_PROB: (0.0, 0.4)
  MOSAIC_PROB: (0.4, 0.8)
#  ASPECT_RATIO_GROUPING: False
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  CROP:
    ENABLED: False
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
OUTPUT_DIR: "output/fcos_r50_diou_test"
VERSION: 2

