MODEL:
  META_ARCHITECTURE: "OneStageDetector"
#  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
#  WEIGHTS: "output/FCOS_MS_X_101_32x8d_dcnv2_2x.pth"
  WEIGHTS: "output/gfl_fcos_dcnv2_x101_fpn_3x_dfl_fixbug/best.pth"
  MASK_ON: False
  KEYPOINT_ON: False
  PIXEL_STD: [57.375, 57.120, 58.395]
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEFORM_ON_PER_STAGE: (False, False, True, True)
    DEFORM_MODULATED: True
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "DFLFCOS"
  FCOS:
    NUM_CLASSES: 1
    NMS_TH: 0.6
    INFERENCE_TH_TEST: 0.35
    PRE_NMS_TOPK_TRAIN: 1000
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TRAIN: 200
    POST_NMS_TOPK_TEST: 200
    LOC_LOSS_TYPE: 'diou'
    NMS_TYPE: 'diou_nms'
    NORM: "GN"
    USE_DEFORMABLE: True
DATASETS:
  TRAIN: ("wheat_coco_train",)
  TEST: ("wheat_coco_val",)
#DATALOADER:
#  MOSAIC_PROB: (0.0, 0.33)
#  MIXUP_PROB: (0.33, 0.34)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  WARMUP_FACTOR: 0.00125
  WARMUP_ITERS: 800
  STEPS: (6000, 8000)
  MAX_ITER: 9000
  CHECKPOINT_PERIOD: 1500
INPUT:
  CROP:
    ENABLED: False
  MIN_SIZE_TRAIN: (864, 896, 928, 960, 992, 1024)
  MAX_SIZE_TEST: 1024
  MIN_SIZE_TEST: 1024
TEST:
  EVAL_PERIOD: 1500
  AUG:
    ENABLED: False
    MIN_SIZES: (1024, 928, 800)
    MAX_SIZE: 1024
    FLIP: True
OUTPUT_DIR: "output/gfl_fcos_dcnv2_x101_fpn_3x_dfl_fixbug_eval"
VERSION: 2

