MODEL:
  META_ARCHITECTURE: "OneStageDetector"
#  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
#  WEIGHTS: "output/FCOS_MS_X_101_32x8d_dcnv2_2x.pth"
  WEIGHTS: "output/qfl_atss_RS_101_fpn_3x_b8_anchor6/model_final.pth"
#  WEIGHTS: "https://hangzh.s3-us-west-1.amazonaws.com/encoding/models/resnest101_detectron-486f69a8.pth"
  MASK_ON: False
  KEYPOINT_ON: False
  PIXEL_MEAN: [123.68, 116.779, 103.939]
  PIXEL_STD: [58.393, 57.12, 57.375]
  BACKBONE:
    NAME: "build_fcos_resnest_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
    DEPTH: 101
    STRIDE_IN_1X1: False
    RADIX: 2
    NORM: "SyncBN"
  FPN:
    NORM: "SyncBN"
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "QFLATSS"
  ATSS:
    NUM_CLASSES: 1
    INFERENCE_TH: 0.43
    NMS_TH: 0.5
    POSITIVE_TYPE: 'ATSS' # how to select positves: ATSS (Ours) , SSC (FCOS), IoU (RetinaNet)
    TOPK: 9 # topk for selecting candidate positive samples from each level
    REGRESSION_TYPE: 'BOX' # regressing from a 'BOX' or a 'POINT'
    POST_NMS_TOPK_TEST: 120
    USE_DCN_IN_TOWER: True
  ANCHOR_GENERATOR:
    SIZES: [[48], [96], [192], [384], [768]]  # One size for each in feature map 8S
    ASPECT_RATIOS: [[1.0,]]  # Three aspect ratios (same for all in feature maps)
    ANGLES: [[0,]]
    OFFSET: 0.0
DATASETS:
  TRAIN: ("wheat_coco_train",)
  TEST: ("wheat_coco_val",)
DATALOADER:
  MOSAIC_PROB: 0.33
  MIXUP_PROB: 0.34
  CUTOUT_PROB: 0.0
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  WARMUP_FACTOR: 0.00125
  WARMUP_ITERS: 800
  STEPS: (12000, 16000)
  MAX_ITER: 18000
  CHECKPOINT_PERIOD: 2000
INPUT:
  FORMAT: "RGB"
  CROP:
    ENABLED: False
  MIN_SIZE_TRAIN: (864, 896, 928, 960, 992, 1024)
  MAX_SIZE_TEST: 1024
  MIN_SIZE_TEST: 1024
TEST:
  PRECISE_BN:
    ENABLED: True
  EVAL_PERIOD: 2000
  AUG:
    ENABLED: True
    MIN_SIZES: (1024,)
    MAX_SIZE: 1024
    FLIP: True
    VERTICAL_FLIP: True
OUTPUT_DIR: "output/qfl_atss_RS_101_fpn_3x_b8_anchor6_eval"
VERSION: 2

