MODEL:
  META_ARCHITECTURE: "ClassificationNetwork"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#  WEIGHTS: "output/R_50_2x/model_final.pth"
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res5"]
  CLASSIFICATION:
    NUM_CLASSES: 1
    IN_FEATURES: ["res5"]
    SCORE_THRESH: 0.5
    FOCAL_LOSS_ALPHA: 1.0
    FOCAL_LOSS_GAMMA: 1.5
DATASETS:
  TRAIN: ("size_chart_train",)
  TEST: ("size_chart_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (6700, 8900)
  MAX_ITER: 11000
  CHECKPOINT_PERIOD: 2000
INPUT:
  MIN_SIZE_TRAIN: (416, 448, 480, 512)
  MAX_SIZE_TEST: 512
  MIN_SIZE_TEST: 416
DATALOADER:
  ASPECT_RATIO_GROUPING: True
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "output/R_50_2x_test"
VERSION: 2
