MODEL:
  META_ARCHITECTURE: "FashionNet"
  #WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  #WEIGHTS: "output/model_0049999.pth"
  MASK_ON: False
  KEYPOINT_ON: False
  BACKBONE:
    NAME: "DenseboxNoBrranchConv32T"
  DENSEBOX:
    OUT_CHANNELS: 128
    OUT_FEATURES: ["res4d"]
  ANCHOR_GENERATOR:
    SIZES: [[32, 64, 128, 256, 512]]
  RETINANET:
    IN_FEATURES: ["res4d"]
    NUM_CLASSES: 13
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
DATASETS:
  TRAIN: ("fashion_train_5w", "fashion_train_user_commodity_5w","fashion_train_commodity_10w","fashion_train_crop_5k")
  #TRAIN: ("fashion_train_test",)
  TEST: ("fashion_validation_merged_v1",)
  #TEST: ("fashion_train_test",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.25
SOLVER:
  IMS_PER_BATCH: 12
  BASE_LR: 0.001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  #MIN_SIZE_TRAIN_SAMPLING: "choice"
TEST:
  EVAL_PERIOD: 10000
OUTPUT_DIR: "./output/densebox"
VERSION: 2