MODEL:
  META_ARCHITECTURE: "FashionNet"
  #WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  #WEIGHTS: "output/mix_add2conv/model_0019999.pth"
  MASK_ON: False
  KEYPOINT_ON: False
  BACKBONE:
    NAME: "build_resnet_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res5"]
    NORM: 'FrozenBN'
  ANCHOR_GENERATOR:
    SIZES: [[32, 64, 128, 256, 512]]
#  FPN:
#    IN_FEATURES: ["res3", "res4", "res5"]
  RETINANET:
    IN_FEATURES: ["res5"]
    NUM_CLASSES: 13
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
  FASHIONNET:
    CLASSIFICATION_HEAD:
      ACTIVATION: 'softmax'
      SCORE_THRESH: 0.5
DATASETS:
  TRAIN: >
   ("fashion_train_5w",
    "fashion_train_user_commodity_5w",
    "fashion_train_commodity_10w",
    "fashion_train_crop_5k",
    "shopee_fashion_train_6k",
    "shopee_fashion_train_3k",)
#  TRAIN: ("shopee_fashion_train_6k", "shopee_fashion_train_3k",)
  TEST: ("fashion_validation_merged_v1", "shopee_fashion_new_test",)
#  TEST: ("shopee_fashion_new_test",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.2
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  #MIN_SIZE_TRAIN_SAMPLING: "choice"
TEST:
  EVAL_PERIOD: 10000
  # export and visualize the error data.
  VIEW_ERROR: False
OUTPUT_DIR: "./output/mix_add2conv"
VERSION: 2